package com.whisperkeyboard

data class VoiceCommand(
    val phrase: String,
    val action: String,
    val value: String,
    val count: Int = 1,
    val aliases: List<String> = emptyList(),
) {
    fun allPhrases(): List<String> = listOf(phrase) + aliases
}

object VoiceCommands {
    val all: List<VoiceCommand> = listOf(
        VoiceCommand("full stop", "text", "."),
        VoiceCommand("comma", "text", ","),
        VoiceCommand("question mark", "text", "?"),
        VoiceCommand("exclamation mark", "text", "!"),
        VoiceCommand("colon", "text", ":"),
        VoiceCommand("semicolon", "text", ";"),
        VoiceCommand("dash", "text", "-"),
        VoiceCommand("hyphen", "text", "-"),
        VoiceCommand("ellipsis", "text", "..."),
        VoiceCommand("open bracket", "text", "("),
        VoiceCommand("close bracket", "text", ")"),
        VoiceCommand("open square bracket", "text", "["),
        VoiceCommand("close square bracket", "text", "]"),
        VoiceCommand("open quote", "text", "\""),
        VoiceCommand("close quote", "text", "\""),
        VoiceCommand("single quote", "text", "'"),
        VoiceCommand("apostrophe", "text", "'"),
        VoiceCommand("slash", "text", "/"),
        VoiceCommand("backslash", "text", "\\"),
        VoiceCommand("at sign", "text", "@"),
        VoiceCommand("hash tag", "text", "#"),
        VoiceCommand("dollar sign", "text", "$"),
        VoiceCommand("percent sign", "text", "%"),
        VoiceCommand("ampersand", "text", "&"),
        VoiceCommand("star", "text", "*"),
        VoiceCommand("plus sign", "text", "+"),
        VoiceCommand("equals sign", "text", "="),
        VoiceCommand("pipe", "text", "|"),
        VoiceCommand("tilde", "text", "~"),
        VoiceCommand("underscore", "text", "_"),
        VoiceCommand("new line", "key", "enter"),
        VoiceCommand("new paragraph", "key", "enter", count = 2),
        VoiceCommand("space bar", "text", " "),
        VoiceCommand("tab", "key", "tab"),
        VoiceCommand("backspace", "key", "backspace"),
        VoiceCommand("delete word", "key", "ctrl_backspace"),
        VoiceCommand("delete line", "key", "ctrl_backspace", count = 10),
        VoiceCommand("undo", "key", "ctrl_z"),
        VoiceCommand("redo", "key", "ctrl_y"),
        VoiceCommand("select all", "key", "ctrl_a"),
        VoiceCommand("all caps", "caps", "upper"),
        VoiceCommand("lower case", "caps", "lower"),
        VoiceCommand("title case", "caps", "title"),
        VoiceCommand("smile emoji", "text", "\uD83D\uDE0A", aliases = listOf("smile face", "smiling face", "happy face")),
        VoiceCommand("laugh emoji", "text", "\uD83D\uDE02", aliases = listOf("laugh face", "laughing face", "laughing emoji")),
        VoiceCommand("heart emoji", "text", "\u2764\uFE0F", aliases = listOf("love emoji", "heart", "love heart")),
        VoiceCommand("thumbs up emoji", "text", "\uD83D\uDC4D", aliases = listOf("thumbs up", "like emoji")),
        VoiceCommand("thumbs down emoji", "text", "\uD83D\uDC4E", aliases = listOf("thumbs down", "dislike emoji")),
        VoiceCommand("clap emoji", "text", "\uD83D\uDC4F", aliases = listOf("clapping", "clap", "clapping emoji")),
        VoiceCommand("fire emoji", "text", "\uD83D\uDD25", aliases = listOf("fire", "lit emoji")),
        VoiceCommand("cry emoji", "text", "\uD83D\uDE22", aliases = listOf("cry face", "crying face", "crying emoji", "sad cry")),
        VoiceCommand("angry emoji", "text", "\uD83D\uDE20", aliases = listOf("angry face", "anger emoji", "mad emoji")),
        VoiceCommand("wink emoji", "text", "\uD83D\uDE09", aliases = listOf("wink face", "winking emoji")),
        VoiceCommand("sad emoji", "text", "\uD83D\uDE14", aliases = listOf("sad face")),
        VoiceCommand("cool emoji", "text", "\uD83D\uDE0E", aliases = listOf("cool face", "sunglasses emoji")),
        VoiceCommand("party emoji", "text", "\uD83C\uDF89", aliases = listOf("party", "celebration emoji")),
        VoiceCommand("pray emoji", "text", "\uD83D\uDE4F", aliases = listOf("pray", "prayer emoji", "namaste", "thank you emoji")),
        VoiceCommand("ok emoji", "text", "\uD83D\uDC4C", aliases = listOf("ok hand", "okay emoji")),
        VoiceCommand("hundred emoji", "text", "\uD83D\uDCAF", aliases = listOf("hundred", "one hundred", "keep it a hundred")),
        VoiceCommand("eyes emoji", "text", "\uD83D\uDC40", aliases = listOf("eyes", "looking emoji")),
        VoiceCommand("rocket emoji", "text", "\uD83D\uDE80", aliases = listOf("rocket", "launch emoji")),
        VoiceCommand("check mark emoji", "text", "\u2705", aliases = listOf("check mark", "tick mark", "green tick")),
        VoiceCommand("cross mark emoji", "text", "\u274C", aliases = listOf("cross mark", "red cross", "x mark")),
    )
}
